### ISSUE TITLE
provisioner returns error while trying to remove dhcp host

### ISSUE THREAD

**Issue by dudymas** [opencrowbar/core#453]
Given 1 admin node and 7 slave nodes, and running:
```
$ crowbar destroy node 8
```

I expted the node (id 8) should be destroyed and the admin node returns to active and ready.

Instead, the admin node (id 1) errors, and attempts to retry return the following for the provisioner-dhcp-database:

```
[2015-02-12T20:36:23+00:00] INFO: Removing d00-25-90-60-4c-44.hivelocity.net-1 host from /etc/dhcp3/hosts.d/

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/provisioner/recipes/update_nodes.rb
================================================================================

ArgumentError
-------------
You must supply a name when declaring a provisioner_bootfile resource

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/provisioner/recipes/update_nodes.rb:188:in `block in from_file'
  /var/chef/cache/cookbooks/provisioner/recipes/update_nodes.rb:176:in `each'
  /var/chef/cache/cookbooks/provisioner/recipes/update_nodes.rb:176:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/provisioner/recipes/update_nodes.rb:

181:        hostname old_node_name
182:        ipaddress "0.0.0.0"
183:        macaddress mac_list[idx]
184:        action :nothing
185:      end
186:      a.run_action(:remove)
187:    end
188>>   a = provisioner_bootfile old_node["bootenv"] do
189:      action :nothing
190:      address mac_list
191:    end
192:    a.run_action(:remove)
193:    a = directory "#{node_dir}/#{old_node_name}" do
194:      action :nothing
195:      recursive true
196:    end
197:    a.run_action(:remove)

[2015-02-12T20:36:23+00:00] ERROR: Running exception handlers
```

**Comment by galthaus** [comment]
This is closed/fixed by #456
