### ISSUE TITLE
Chef Client fails if  Chef Patch is applied

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#582]
State  : Running, pid: 11793
Existing lock /var/run/yum.pid: another copy is running as pid 11815.
Another app is currently holding the yum lock; waiting for it to exit...
The other application is: yum
Memory : 49 M RSS (265 MB VSZ)
Started: Thu May 7 18:33:48 2015 - 00:01 ago
State : Running, pid: 11815
Metadata Cache Created
//tmp/scriptjig-Dsq1yz/chef-client/01-install-client.sh@10(): yum install -y chef
Package chef-11.16.4-1.el6.x86_64 already installed and latest version
Nothing to do
//tmp/scriptjig-Dsq1yz/chef-client/01-install-client.sh@13(): cd /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/linux/
//tmp/scriptjig-Dsq1yz/chef-client/01-install-client.sh@14(): yum install -y patch
Package patch-2.7.1-8.el7.x86_64 already installed and latest version
Nothing to do
//tmp/scriptjig-Dsq1yz/chef-client/01-install-client.sh@15(): patch
patching file platform.rb
Reversed (or previously applied) patch detected! Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file platform.rb.rej
/tmp/scriptjig-Dsq1yz/runner@58(): exit 1

**Comment by VictorLowther** [comment]
This was caused by the runlist locking being broken, and should be resolved.

**Comment by sjensen** [comment]
Failed again..:(

RuntimeError: Script jig run for chef-client on d08-00-27-82-b7-d3.scottco.com failed! (status = 1)
Out: /tmp/scriptjig-A1jakl/runner@5(): shopt -s nullglob extglob globstar
/tmp/scriptjig-A1jakl/runner@6(): export TMPDIR=/tmp/scriptjig-A1jakl
/tmp/scriptjig-A1jakl/runner@6(): TMPDIR=/tmp/scriptjig-A1jakl
/tmp/scriptjig-A1jakl/runner@7(): export ROLE=chef-client
/tmp/scriptjig-A1jakl/runner@7(): ROLE=chef-client
/tmp/scriptjig-A1jakl/runner@10(): export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
/tmp/scriptjig-A1jakl/runner@10(): DEBIAN_FRONTEND=noninteractive
/tmp/scriptjig-A1jakl/runner@10(): DEBCONF_NONINTERACTIVE_SEEN=true
/tmp/scriptjig-A1jakl/runner@11(): export LC_ALL=C LANGUAGE=C LANG=C
/tmp/scriptjig-A1jakl/runner@11(): LC_ALL=C
/tmp/scriptjig-A1jakl/runner@11(): LANGUAGE=C
/tmp/scriptjig-A1jakl/runner@11(): LANG=C
/tmp/scriptjig-A1jakl/runner@54(): mkdir -p /tmp/scriptjig-A1jakl/attrs
/tmp/scriptjig-A1jakl/runner@55(): mkdir -p /tmp/scriptjig-A1jakl/logs
/tmp/scriptjig-A1jakl/runner@57(): for script in '"$TMPDIR/$ROLE/"*.sh'
/tmp/scriptjig-A1jakl/runner@58(): . /tmp/scriptjig-A1jakl/chef-client/01-install-client.sh
/tmp/scriptjig-A1jakl/runner@58(): tee /tmp/scriptjig-A1jakl/logs/01-install-client.sh.log
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@3(): [[ -f /etc/os-release ]]
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@4(): . /etc/os-release
///etc/os-release@1(): NAME='CentOS Linux'
///etc/os-release@2(): VERSION='7 (Core)'
///etc/os-release@3(): ID=centos
///etc/os-release@4(): ID_LIKE='rhel fedora'
///etc/os-release@5(): VERSION_ID=7
///etc/os-release@6(): PRETTY_NAME='CentOS Linux 7 (Core)'
///etc/os-release@7(): ANSI_COLOR='0;31'
///etc/os-release@8(): CPE_NAME=cpe:/o:centos:centos:7
///etc/os-release@9(): HOME_URL=https://www.centos.org/
///etc/os-release@10(): BUG_REPORT_URL=https://bugs.centos.org/
///etc/os-release@12(): CENTOS_MANTISBT_PROJECT=CentOS-7
///etc/os-release@13(): CENTOS_MANTISBT_PROJECT_VERSION=7
///etc/os-release@14(): REDHAT_SUPPORT_PRODUCT=centos
///etc/os-release@15(): REDHAT_SUPPORT_PRODUCT_VERSION=7
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@7(): which chef-client
which: no chef-client in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@8(): [[ -f /etc/redhat-release ]]
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@9(): yum -y makecache
Metadata Cache Created
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@10(): yum install -y chef
Existing lock /var/run/yum.pid: another copy is running as pid 10009.
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  23 M RSS (238 MB VSZ)
    Started: Tue May 12 15:07:02 2015 - 00:10 ago
    State  : Sleeping, pid: 10009
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  26 M RSS (246 MB VSZ)
    Started: Tue May 12 15:07:02 2015 - 00:12 ago
    State  : Sleeping, pid: 10009
Existing lock /var/run/yum.pid: another copy is running as pid 11805.
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  47 M RSS (263 MB VSZ)
    Started: Tue May 12 15:07:14 2015 - 00:02 ago
    State  : Sleeping, pid: 11805
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  54 M RSS (271 MB VSZ)
    Started: Tue May 12 15:07:14 2015 - 00:04 ago
    State  : Running, pid: 11805
Existing lock /var/run/yum.pid: another copy is running as pid 11827.
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  48 M RSS (265 MB VSZ)
    Started: Tue May 12 15:07:19 2015 - 00:01 ago
    State  : Running, pid: 11827
Package chef-11.16.4-1.el6.x86_64 already installed and latest version
Nothing to do
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@13(): cd /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.4.0/lib/ohai/plugins/linux/
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@14(): yum install -y patch
Existing lock /var/run/yum.pid: another copy is running as pid 10274.
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  23 M RSS (238 MB VSZ)
    Started: Tue May 12 15:07:02 2015 - 00:20 ago
    State  : Sleeping, pid: 10274
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  26 M RSS (246 MB VSZ)
    Started: Tue May 12 15:07:02 2015 - 00:22 ago
    State  : Sleeping, pid: 10274
Package patch-2.7.1-8.el7.x86_64 already installed and latest version
Nothing to do
//tmp/scriptjig-A1jakl/chef-client/01-install-client.sh@15(): patch
patching file platform.rb
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file platform.rb.rej
/tmp/scriptjig-A1jakl/runner@58(): exit 1

Err: Warning: Permanently added '192.168.125.83' (RSA) to the list of known hosts.

Backtrace:
/opt/opencrowbar/core/rails/app/models/jig.rb:42:in `die'
/opt/opencrowbar/core/rails/app/models/barclamp_crowbar/jig.rb:50:in `run'
/opt/opencrowbar/core/rails/app/models/jig.rb:116:in `run_job'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/performable_method.rb:30:in `perform'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/usr/lib64/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/usr/lib64/ruby/2.1.0/timeout.rb:101:in `call'
/usr/lib64/ruby/2.1.0/timeout.rb:101:in `timeout'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/usr/lib64/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/usr/lib64/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in `run'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in `block in run_process'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `block in start_proc'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call_as_daemon'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:269:in `start_proc'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:295:in `start'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/controller.rb:56:in `run'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:193:in `block in run_proc'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
/var/cache/crowbar/gems/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:192:in `run_proc'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in `run_process'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in `block in daemonize'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `times'
/var/cache/crowbar/gems/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'
script/delayed_job:5:in `<main>'

**Comment by galthaus** [comment]
I wonder if I built RPMs with all the fixes.  I thought I had.

**Comment by sjensen** [comment]
Same issue although on 1 failed this time.  I have not retried the noderole as that resolves it in case someone wanted to take a look.

**Comment by VictorLowther** [comment]
I am not at my system right now, but you should be able to look in
production.log for lines that have "Run: " in them.
On May 12, 2015 10:15 AM, "SCOTT JENSEN" <notifications@github.com> wrote:
>
> Same issue although on 1 failed this time. I have not retried the
noderole as that resolves it in case someone wanted to take a look.
